// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsETeWkaHmWI4njMEt4ABbSzgyPolBsRE',
    appId: '1:931606469113:web:990b734655b61ed8870528',
    messagingSenderId: '931606469113',
    projectId: 'sponser-48a3a',
    authDomain: 'sponser-48a3a.firebaseapp.com',
    storageBucket: 'sponser-48a3a.appspot.com',
    measurementId: 'G-XT69J0DZWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoBgEQT0m30mTr-l5YxPYeVmTig9WTSwU',
    appId: '1:931606469113:android:ec26e41bb1749dc9870528',
    messagingSenderId: '931606469113',
    projectId: 'sponser-48a3a',
    storageBucket: 'sponser-48a3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQEx_8Pm6IFOtnzr1ldj8_TfDOWdBbhoA',
    appId: '1:931606469113:ios:421dbc79d9db8b43870528',
    messagingSenderId: '931606469113',
    projectId: 'sponser-48a3a',
    storageBucket: 'sponser-48a3a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQEx_8Pm6IFOtnzr1ldj8_TfDOWdBbhoA',
    appId: '1:931606469113:ios:421dbc79d9db8b43870528',
    messagingSenderId: '931606469113',
    projectId: 'sponser-48a3a',
    storageBucket: 'sponser-48a3a.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
